"""Agent brain — persistent JSON memory (goals, theses, trades, state, chat, UX)."""

from brain.chat_store import (
    append_turn,
    chat_for_agent,
    chat_for_ui,
    compress_chat,
    ensure_chat_file,
    load_chat,
    prepare_chat_for_session,
)
from brain.policy import (
    THESIS_AUTONOMY_BLURB,
    THESIS_AUTONOMY_POLICY,
    auto_sweep_prompt,
    build_auto_sweep_context,
)
from brain.store import (
    active_theses,
    brain_overview,
    current_goals,
    enrich_holdings,
    ensure_brain_initialized,
    format_memory_for_llm,
    load_goals,
    load_holdings_book,
    load_state,
    load_theses,
    load_trades,
    rebuild_state_summary,
    recent_trades,
    record_trade,
    save_goals,
    save_holdings_book,
    thesis_for_symbol,
    thesis_view,
    upsert_thesis,
)
from brain.scheduler import (
    get_auto_status,
    notify_ux_changed,
    run_auto_review_now,
    start_auto_scheduler,
)
from brain.ux_state import ensure_ux_state, load_ux_state, mark_auto_run, save_ux_state

__all__ = [
    "active_theses",
    "append_turn",
    "brain_overview",
    "chat_for_agent",
    "chat_for_ui",
    "compress_chat",
    "current_goals",
    "enrich_holdings",
    "ensure_brain_initialized",
    "ensure_chat_file",
    "ensure_ux_state",
    "format_memory_for_llm",
    "get_auto_status",
    "load_chat",
    "load_goals",
    "load_holdings_book",
    "load_state",
    "load_theses",
    "load_trades",
    "load_ux_state",
    "mark_auto_run",
    "notify_ux_changed",
    "prepare_chat_for_session",
    "rebuild_state_summary",
    "recent_trades",
    "record_trade",
    "run_auto_review_now",
    "save_goals",
    "save_holdings_book",
    "save_ux_state",
    "start_auto_scheduler",
    "thesis_for_symbol",
    "thesis_view",
    "upsert_thesis",
    "THESIS_AUTONOMY_BLURB",
    "THESIS_AUTONOMY_POLICY",
    "auto_sweep_prompt",
    "build_auto_sweep_context",
]
